version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.15.0
    branches:
      ignore:
        - gh-pages # list of branches to ignore
        - /release\/.*/ # or ignore regexes
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install dependences
          command: npm i && npm run bootstrap
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm run test:cov
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)
