export const NEST_STACK_AXIOS_INSTANCE_TOKEN =
  'NEST_STACK_AXIOS_INSTANCE_TOKEN';
export const NEST_STACK_HTTP_MODULE_ID = 'NEST_STACK_HTTP_MODULE_ID';
export const NEST_STACK_HTTP_MODULE_OPTIONS = 'NEST_STACK_HTTP_MODULE_OPTIONS';
